version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Building the Docker image...
      - cp target/HelloWorld-1.war HelloWorld.war
      - echo 'FROM tomcat:jre11' > Dockerfile
      - echo 'RUN rm -rf /usr/local/tomcat/webapps' >> Dockerfile
      - echo 'RUN mkdir /usr/local/tomcat/webapps' >> Dockerfile
      - echo 'ADD HelloWorld.war /usr/local/tomcat/webapps/ROOT.war' >> Dockerfile
      - docker build -t helloworld .
      - docker tag helloworld:latest $ECR_REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"helloworld-container","imageUri":"%s"}]' $ECR_REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json